platform :ios, '10.0'
use_frameworks!
target 'JKSwiftExtension_Example' do
  pod 'JKSwiftExtension', :path => '../'

  pod 'SnapKit'
  
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
#              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
#      end
#    end
#  end
#end

