use_frameworks!
target 'JKSwiftExtension_Example' do
  pod 'JKSwiftExtension', :path => '../'

  # pod 'RxSwift'
  # pod 'RxCocoa'
  pod 'FDFullscreenPopGesture'
  pod 'MJRefresh'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'SwiftLint', '0.46.3', configurations:['Debug']
end
